### ISSUE TITLE
Terminal closing when running any sylph command

### ISSUE THREAD

**Issue by pavlos-elpidorou** [mmcc007/sylph#115]
hello, 
i have installed sylph using the `flutter pub global activate sylph` command and it installed ok.
But when i run any sylph command my terminal window closes instantly...

how to fix it?

I'm running it on Windows 10.

**Comment by SalihCanBinboga** [comment]
Hello @pavlos-elpidorou  can you try this steps,

- if exist ios pool remove all
- android pool devices if more than one just only one left
- use this device : 
`
      - name: Google Pixel 3
        model: Pixel 3
        os: 10
`

and try again or use this yaml

```
tmp_dir: /tmp/sylph
artifacts_dir: /tmp/sylph_artifacts
sylph_timeout: 720
concurrent_runs: true


project_name: App Integration Test
default_job_timeout: 10

device_pools:
  - pool_name: android pool 1
    pool_type: android
    devices:
      - name: Google Pixel 3
        model: Pixel 3
        os: 10
		
test_suites:

  - test_suite: example test 1
    main: test_driver/main.dart
    tests:
      - test_driver/main_test.dart
    pool_names:
      - android pool 1
    job_timeout: 15
```
